### ISSUE TITLE
multiplane issues

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guide-rest-client-java#50]
- [x] the statement "Which responds with the following JSON" does not make sense where the JSON file on the right side.
- [x] Create the ArtistResource class. It is not "Create". It should "Replace". If the ArtistResource.java is removed from the start directory, the command `mvn install` won't work.
- [x] should format ConsumingRestTest
`assertEquals("Expected names of artists does not match", expected.name, actual[0].name);`
- [x] the hotspot for  "For your test classes to have access to JSON-B, the following dependency has been added in your pom.xml" misses a line

**Comment by justineechen** [comment]
https://github.com/OpenLiberty/guide-rest-client-java/commit/4963eac8ea46ad06c42f02a940f46c16c7d36e20
