### ISSUE TITLE
Multipane - Post-Publishing tests

### ISSUE THREAD

**Issue by proubatsis** [OpenLiberty/guide-rest-client-java#52]
- [x] Check appearance (contents, headings, paragraphs, code snippets, outputs, links, hotspots) of the guide on test site, ie, qa-guides
- [x] Read through the guide 
- [x] Clone repo and test finish directory with no error
- [x] Run `diff -r start/ finish/` 
- [x] Follow the instruction in the guide to test that it is working
- [x] Use the `copy` buttons instead of typing 
- [x] Links open in new tab
- [x] Action arrows do not highlight any code
- [x] Update action arrows have hotspotted text underneath
- [x] Full files mentioned in the guide as hotspots should not highlight any code
- [x] Hovering over code commands should switch to the right file

**Comment by proubatsis** [comment]
* Link leads to a 404 page: `http://json-b.net/users-guide.html`
* Hotspots highlight the wrong thing
> For the purpose of this guide, you are given two POJOs. The Artist object has two instance members name and albums, which map to the artist name and the collection of the albums they have written. 
* Hotspot doesn't render correctly
![image](https://user-images.githubusercontent.com/8409464/53600686-24248c00-3b78-11e9-8882-f242daac16d2.png)
* The guide never tells you to start the server before the first `mvn compile`

**Comment by andrewdes** [comment]
Changes merged here: https://github.com/OpenLiberty/guide-rest-client-java/pull/53
