### ISSUE TITLE
Improve description for JSON-B mapping rules

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guide-rest-client-java#54]
Specifically:
```If these names do not match, then getters and setters are matched to JSON keys and the instance members are set explicitly. If the getter and setter signatures do not match any key names, then deserialization fails.```

Call out what "these names" are.  And/or, describe with actual examples.

@tjwatson @neuwerk

**Comment by tjwatson** [comment]
@yeekangc did you mean to tag me in this issue?  If so can you post a link to the guide in question.  Not sure I have the full context to help.

**Comment by yeekangc** [comment]
Sorry, I tagged the wrong person.  I have meant to tag @andymc12 and the other Thomas (@neuwerk).  Somehow, I tagged both Thomas-es.  Oops!

**Comment by andymc12** [comment]
I think we'll want @aguibert to also review the final text, but possibly we could change it to something like:
```
JSON-B will attempt to match the JSON key with a Java field or method
annotated with `@JsonbProperty` where the value in the annotation exactly
matches the JSON key.  If no annotation exists with the given JSON key, then
JSON-B will attempt to find a matching field with the same name.  If a match
still cannot be found, JSON-B will then attempt to find a matching getter (for
serialization) or setter (for de-serialization) method whose property name
matches the JSON key.  A property name for `String getWidget()` / 
`void setWidget(String widget)` would be "widget".  If no matching 
getter/setter method can be found, then serialization/de-serialization will fail
with an exception.
```

I don't like that it is so much longer, but maybe that is more clear?  What do you guys think?

**Comment by yeekangc** [comment]
I think it's clearer.  Thank you, Andy.  We can revise it further to make it more concise.

@gkwan-ibm
