### ISSUE TITLE
Some text and user experience improvement

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guide-rest-client-java#61]
- [x] the paragraph in the intro section seems cut off and the sentence should end with a punctuation: 

The REST service that provides the artists and albums resources has already been written for you and is accessible at the following link when the server is running http://localhost:9080/artists

Which responds with the artists.json

- [x] "try what you'll build" section is missing

- [x] the "Starting the service" section seems like the "try what you'll build" content, not sure why it's a section on its own..

- [x] there're some comments in the `Artist` and `Consumer` classes that can be improved or cleaned up

- [x] the heading "Introducing JSON-B and JSON-P" can be re-phased to be more relevant and specific to the guide **(proposed an update)**.

- [x] the heading "Creating additional REST resources" can be re-phased to be more relevant and specific as well. **(proposed an update)**.

**Comment by justineechen** [comment]
> "try what you'll build" section is missing
> the "Starting the service" section seems like the "try what you'll build" content, not sure why it's a section on its own..

- The rest-client-java guide has a `Starting the service` section that shows users the existing application that they will work with so we decided not to add a `Try what you'll build` section when we were reviewing which guides were missing this section. It's named `Starting the service` because the user won't be building this later on. 

> there're some comments in the Artist and Consumer classes that can be improved or cleaned up

- I didn't see any comments in the Consumer class, do you think we should add any? I'm not sure if comments are that necessary since we describe the classes in the guide

> the heading "Introducing JSON-B and JSON-P" can be re-phased to be more relevant and specific to the guide
> the heading "Creating additional REST resources" can be re-phased to be more relevant and specific as well

- I'm not sure what to change these two yet.. I think they are relevant but I can ping ID for suggestions. If anything, I find the "Creating POJOs" title to be wrong since the POJOs are already created for the user.

**Comment by evelinec** [comment]
- [ ] I think there needs to be some linkage between the "Starting the service" section and the "Creating POJOs" section. ie, change the sentence, "To deserialize a JSON message, start with creating Plain Old Java Objects.." to "To deserialize a JSON message in the `artists` service, start with creating Plain Old Java Objects.."

- [ ] Altho I still think that a "try what you'll build" section is possible, just need to have more transition sentence/words to make it flow smoothly end-to-end

- [ ] The `Album` class has some comments that can be clean up as well. Not the `Consumer` class. Typed that one wrong last time. 

- [ ] I still think the heading "Introducing JSON-B and JSON-P" can be made more relevant. Overall, the flow of this guide is bit different from other guides. Need some thinking for it. 

The current fixes for your PR is good, and if you can address the comments in the `Albums` class as well. We can leave the rest for further consideration for now.

**Comment by evelinec** [comment]
The checked points so far are addressed in #65. Others we can consider for later. Move the issue back to the backlog for now.

**Comment by gkwan-ibm** [comment]
checked  "try what you'll build" section is missing because it was addressed

**Comment by gkwan-ibm** [comment]
checked the "Starting the service" section.... because it is used to start the dev mode

**Comment by gkwan-ibm** [comment]
close
- issues were addressed
