### ISSUE TITLE
json-b dependency reference in pom.xml highlights the wrong dependency

### ISSUE THREAD

**Issue by cthigh** [OpenLiberty/guide-rest-client-java#77]
In the **Consuming the REST resource** section, there is a paragraph that explains the JSON-B dependencies:

_Open Liberty’s JSON-B feature on Maven Central includes the JSON-B provider through transitive dependencies. The **JSON-B provider** has been added as a dependency in your pom.xml_.  (btw, missing a .)

Hovering over **JSON-B provider** highlights the yasson dependency in the pom.xml that was provided for test.
```
        <dependency>
            <groupId>org.eclipse</groupId>
            <artifactId>yasson</artifactId>
            <version>1.0.1</version>
            <scope>test</scope>
        </dependency>
```

It would make sense for this paragraph to highlight the json-1.0 feature instead.  Also the paragraph says json-b is included using transitive dependencies - this seems like a direct dependency, so I find this sentence confusing.
```
       <dependency>
            <groupId>io.openliberty.features</groupId>
            <artifactId>jsonb-1.0</artifactId>
            <type>esa</type>
            <scope>provided</scope>
        </dependency>
```

Later on in the guide, the yasson dependency is described accurately in the testing section which makes sense.

**Comment by DannyS03** [comment]
- Hotspot issue addressed in: https://github.com/OpenLiberty/guide-rest-client-java/pull/76 and `JSON-B provider` points to 

```
       <dependency>
            <groupId>io.openliberty.features</groupId>
            <artifactId>jsonb-1.0</artifactId>
            <type>esa</type>
            <scope>provided</scope>
        </dependency>
```
